server:
  port: 8080

spring:
  # 多线程执行器
  task:
    execution:
      pool:
        core-size: 40
        max-size: 40
        keep-alive: 60s
        queue-capacity: 50000
    # Spring 执行器配置，对应 TaskExecutionProperties 配置类。对于 Spring 异步任务，会使用该执行器。
    executor-echo:
      thread-name-prefix: task-echo- # 线程池的线程名的前缀。默认为 task- ，建议根据自己应用来设置
      pool: # 线程池相关
        core-size: 8 # 核心线程数，线程池创建时候初始化的线程数。默认为 8 。
        max-size: 20 # 最大线程数，线程池最大的线程数，只有在缓冲队列满了之后，才会申请超过核心线程数的线程。默认为 Integer.MAX_VALUE
        keep-alive: 60s # 允许线程的空闲时间，当超过了核心线程之外的线程，在空闲时间到达之后会被销毁。默认为 60 秒
        queue-capacity: 200 # 缓冲队列大小，用来缓冲执行任务的队列的大小。默认为 Integer.MAX_VALUE 。
        allow-core-thread-timeout: true # 是否允许核心线程超时，即开启线程池的动态增长和缩小。默认为 true 。
      shutdown:
        wait-for-tasks-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
        await-termination-seconds: 60 # 等待任务完成的最大时长，单位为秒。默认为 0 ，根据自己应用来设置
    # Spring 执行器配置，对应 TaskExecutionProperties 配置类。对于 Spring 异步任务，会使用该执行器。
    executor-single:
      thread-name-prefix: task-single- # 线程池的线程名的前缀。默认为 task- ，建议根据自己应用来设置
      pool: # 线程池相关
        core-size: 1 # 核心线程数，线程池创建时候初始化的线程数。默认为 8 。
        max-size: 1 # 最大线程数，线程池最大的线程数，只有在缓冲队列满了之后，才会申请超过核心线程数的线程。默认为 Integer.MAX_VALUE
        keep-alive: 60s # 允许线程的空闲时间，当超过了核心线程之外的线程，在空闲时间到达之后会被销毁。默认为 60 秒
        queue-capacity: 1000 # 缓冲队列大小，用来缓冲执行任务的队列的大小。默认为 Integer.MAX_VALUE 。
        allow-core-thread-timeout: true # 是否允许核心线程超时，即开启线程池的动态增长和缩小。默认为 true 。
      shutdown:
        wait-for-tasks-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
        await-termination-seconds: 60 # 等待任务完成的最大时长，单位为秒。默认为 0 ，根据自己应用来设置

    # 对应 RedisProperties 类
    redis:
      host: 127.0.0.1
      port: 6379
      #    password: # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
      database: 0 # Redis 数据库号，默认为 0 。
      timeout: 0 # Redis 连接超时时间，单位：毫秒。
      # 对应 RedissonProperties 类
#      redisson:
#        config: classpath:redisson.yml # 具体的每个配置项，见 org.redisson.config.Config 类。


  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/high_concurrency?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# 日志级别
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: info
